version: '3'
services:
  db:
    image: postgis/postgis:13-3.1-alpine
    env_file: ./docker/db/.env
    volumes:
      - ./docker/data/db:/var/lib/postgresql/data

  cache:
    image: redis:6

  directus:
    build: ./docker/directus
    env_file: ./src/directus/.env
    volumes:
      - ./src/directus/uploads:/directus/uploads
      - ./src/directus/extensions:/directus/extensions
      - ./src/directus/schema/:/directus/schema
      - ./src/directus/roles/:/directus/roles
      - ./src/directus/presets/:/directus/presets
      - ./src/directus/webhooks/:/directus/webhooks
      - ./src/directus/translations/:/directus/translations
      - ./src/directus/flows/:/directus/flows
      - ./src/directus/cli/:/directus/cli
      - ./src/directus/.env/:/directus/.env
    depends_on:
    - cache
    - db

  frontend:
    build: ./docker/frontend
    volumes:
      - ./src/frontend:/frontend
    env_file: ./src/frontend/.env
    depends_on:
    - directus
