version: '3'
services:
  db:
    ports:
      - "5432:5432"

  directus:
    ports:
      - "8081:8055"
    command: ["sh", "/start_dev.sh"]

  frontend:
    ports:
      - "8080:3000"
      - "24678:24678"
    command: ["sh", "/start_dev.sh"]
