name: AdminLokalteam
icon: supervised_user_circle
description: null
ip_access: null
enforce_tfa: false
admin_access: false
app_access: true
permissions:
  - collection: bewertungen_massnahmen
    action: read
    permissions:
      _and:
        - lokalteam_id:
            _in:
              - $CURRENT_USER.lokalteams.lokalteam_id
    validation: {}
    presets: null
    fields:
      - "*"
  - collection: lokalteam
    action: read
    permissions:
      _and:
        - id:
            _in:
              - $CURRENT_USER.lokalteams.lokalteam_id
    validation: {}
    presets: null
    fields:
      - id
      - status
      - sort
      - name
      - slug
      - admin_id
      - user_updated
      - date_created
      - user_created
      - date_updated
  - collection: ratings_measures
    action: read
    permissions:
      _and:
        - localteam_id:
            _in:
              - $CURRENT_USER.localteams.localteam_id
    validation: null
    presets: null
    fields:
      - measure_id
      - rating
      - approved
      - Source
      - applicable
      - status
      - user_updated
      - date_updated
      - id
  - collection: ratings_measures
    action: update
    permissions:
      _and:
        - localteam_id:
            _in:
              - $CURRENT_USER.localteams.localteam_id
    validation: null
    presets: null
    fields:
      - status
      - rating
      - applicable
      - Source
  - collection: municipalities
    action: read
    permissions:
      _and:
        - localteam_id:
            _in:
              - $CURRENT_USER.localteams.localteam_id
    validation: {}
    presets: null
    fields:
      - status
      - user_updated
      - date_updated
      - name
      - municipality_type
      - details
      - state
      - population
      - mayor
      - party_mayor
      - scores
      - score_total
      - score_transport
      - score_energy
      - score_iec
      - score_ann
      - score_cpma
      - score_bh
      - id
      - place
      - description
  - collection: municipalities
    action: update
    permissions:
      _and:
        - localteam_id:
            _in:
              - $CURRENT_USER.localteams.localteam_id
    validation: {}
    presets: null
    fields:
      - status
      - user_updated
      - date_updated
      - municipality_type
      - details
      - state
      - population
      - mayor
      - party_mayor
      - description
  - collection: measures
    action: read
    permissions:
      _and:
        - status:
            _eq: published
    validation: {}
    presets: null
    fields:
      - name
      - sector
      - impact
      - weight
      - feasibility
      - feasibility_political
      - feasibility_economical
      - description
      - verification_description
      - notes
      - id
      - status
