id: 3a964766-0e61-4140-90ff-38654594cda2
name: EditorMeasures
icon: supervised_user_circle
description: null
ip_access: null
enforce_tfa: false
admin_access: false
app_access: true
permissions:
  - role: 3a964766-0e61-4140-90ff-38654594cda2
    collection: directus_files
    action: create
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - role: 3a964766-0e61-4140-90ff-38654594cda2
    collection: directus_files
    action: read
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - role: 3a964766-0e61-4140-90ff-38654594cda2
    collection: directus_files
    action: update
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - role: 3a964766-0e61-4140-90ff-38654594cda2
    collection: directus_files
    action: delete
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - role: 3a964766-0e61-4140-90ff-38654594cda2
    collection: directus_dashboards
    action: create
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - role: 3a964766-0e61-4140-90ff-38654594cda2
    collection: directus_dashboards
    action: read
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - role: 3a964766-0e61-4140-90ff-38654594cda2
    collection: directus_dashboards
    action: update
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - role: 3a964766-0e61-4140-90ff-38654594cda2
    collection: directus_dashboards
    action: delete
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - role: 3a964766-0e61-4140-90ff-38654594cda2
    collection: directus_panels
    action: create
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - role: 3a964766-0e61-4140-90ff-38654594cda2
    collection: directus_panels
    action: read
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - role: 3a964766-0e61-4140-90ff-38654594cda2
    collection: directus_panels
    action: update
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - role: 3a964766-0e61-4140-90ff-38654594cda2
    collection: directus_panels
    action: delete
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - role: 3a964766-0e61-4140-90ff-38654594cda2
    collection: directus_folders
    action: create
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - role: 3a964766-0e61-4140-90ff-38654594cda2
    collection: directus_folders
    action: read
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - role: 3a964766-0e61-4140-90ff-38654594cda2
    collection: directus_folders
    action: update
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - role: 3a964766-0e61-4140-90ff-38654594cda2
    collection: directus_folders
    action: delete
    permissions: {}
    validation: null
    presets: null
    fields: null
  - role: 3a964766-0e61-4140-90ff-38654594cda2
    collection: directus_users
    action: read
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - role: 3a964766-0e61-4140-90ff-38654594cda2
    collection: directus_users
    action: update
    permissions:
      id:
        _eq: $CURRENT_USER
    validation: null
    presets: null
    fields:
      - first_name
      - last_name
      - email
      - password
      - location
      - title
      - description
      - avatar
      - language
      - theme
      - tfa_secret
  - role: 3a964766-0e61-4140-90ff-38654594cda2
    collection: directus_roles
    action: read
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - role: 3a964766-0e61-4140-90ff-38654594cda2
    collection: directus_shares
    action: read
    permissions:
      _or:
        - role:
            _eq: $CURRENT_ROLE
        - role:
            _null: true
    validation: null
    presets: null
    fields:
      - "*"
  - role: 3a964766-0e61-4140-90ff-38654594cda2
    collection: directus_shares
    action: create
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - role: 3a964766-0e61-4140-90ff-38654594cda2
    collection: directus_shares
    action: update
    permissions:
      user_created:
        _eq: $CURRENT_USER
    validation: null
    presets: null
    fields:
      - "*"
  - role: 3a964766-0e61-4140-90ff-38654594cda2
    collection: directus_shares
    action: delete
    permissions:
      user_created:
        _eq: $CURRENT_USER
    validation: null
    presets: null
    fields:
      - "*"
  - role: 3a964766-0e61-4140-90ff-38654594cda2
    collection: directus_flows
    action: read
    permissions:
      trigger:
        _eq: manual
    validation: null
    presets: null
    fields:
      - id
      - status
      - name
      - icon
      - color
      - options
      - trigger
  - role: 3a964766-0e61-4140-90ff-38654594cda2
    collection: measures
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
  - role: 3a964766-0e61-4140-90ff-38654594cda2
    collection: measures
    action: update
    permissions: {}
    validation: {}
    presets: null
    fields:
      - sort
      - user_created
      - date_created
      - user_updated
      - date_updated
      - name
      - sector
      - impact
      - weight
      - feasibility
      - feasibility_political
      - feasibility_economical
      - description
      - verification_description
      - notes
      - id
  - role: 3a964766-0e61-4140-90ff-38654594cda2
    collection: measures
    action: create
    permissions: {}
    validation: {}
    presets: null
    fields:
      - id
      - sort
      - user_created
      - date_created
      - user_updated
      - date_updated
      - name
      - slug
      - sector
      - impact
      - weight
      - feasibility
      - feasibility_political
      - feasibility_economical
      - description
      - verification_description
      - notes
