id: 18781584-6436-49b7-a69d-69f4f5e5db8b
name: EditorLokalteam
icon: supervised_user_circle
description: null
ip_access: null
enforce_tfa: false
admin_access: false
app_access: true
permissions:
  - role: 18781584-6436-49b7-a69d-69f4f5e5db8b
    collection: directus_users
    action: read
    permissions:
      _and:
        - id:
            _eq: $CURRENT_USER
    validation: null
    presets: null
    fields:
      - "*"
  - role: 18781584-6436-49b7-a69d-69f4f5e5db8b
    collection: directus_roles
    action: read
    permissions:
      _and:
        - id:
            _eq: $CURRENT_USER
    validation: null
    presets: null
    fields:
      - "*"
  - role: 18781584-6436-49b7-a69d-69f4f5e5db8b
    collection: directus_shares
    action: read
    permissions:
      _or:
        - role:
            _eq: $CURRENT_ROLE
        - role:
            _null: true
    validation: null
    presets: null
    fields:
      - "*"
  - role: 18781584-6436-49b7-a69d-69f4f5e5db8b
    collection: directus_shares
    action: create
    permissions: {}
    validation: null
    presets: null
    fields:
      - "*"
  - role: 18781584-6436-49b7-a69d-69f4f5e5db8b
    collection: directus_shares
    action: update
    permissions:
      user_created:
        _eq: $CURRENT_USER
    validation: null
    presets: null
    fields:
      - "*"
  - role: 18781584-6436-49b7-a69d-69f4f5e5db8b
    collection: directus_shares
    action: delete
    permissions:
      user_created:
        _eq: $CURRENT_USER
    validation: null
    presets: null
    fields:
      - "*"
  - role: 18781584-6436-49b7-a69d-69f4f5e5db8b
    collection: lokalteam
    action: read
    permissions:
      _and:
        - id:
            _eq: $CURRENT_USER.lokalteam_id
    validation: {}
    presets: null
    fields:
      - "*"
