id: d09e2c25-a977-41fc-aa73-9238fcf20a9b
name: frontend
icon: web_asset
description: null
ip_access: null
enforce_tfa: false
admin_access: false
app_access: false
permissions:
  - role: d09e2c25-a977-41fc-aa73-9238fcf20a9b
    collection: ratings_measures
    action: read
    permissions:
      _and:
        - status:
            _eq: published
        - approved:
            _eq: true
        - measure_id:
            status:
              _eq: published
        - localteam_id:
            municipality_id:
              status:
                _eq: published
    validation: null
    presets: null
    fields:
      - applicable
      - rating
      - localteam_id
      - measure_id
      - id
      - sort
      - Source
  - role: d09e2c25-a977-41fc-aa73-9238fcf20a9b
    collection: pages
    action: read
    permissions:
      _and:
        - status:
            _eq: published
    validation: null
    presets: null
    fields:
      - id
      - name
      - menus
      - contents
      - slug
      - sort
  - role: d09e2c25-a977-41fc-aa73-9238fcf20a9b
    collection: municipalities
    action: read
    permissions:
      _and:
        - status:
            _eq: published
    validation: null
    presets: null
    fields:
      - id
      - sort
      - name
      - slug
      - municipality_type
      - details
      - score_cpma
      - score_iec
      - score_transport
      - scores
      - mayor
      - state
      - population
      - party_mayor
      - score_energy
      - score_total
      - score_ann
      - score_bh
  - role: d09e2c25-a977-41fc-aa73-9238fcf20a9b
    collection: measures
    action: read
    permissions:
      _and:
        - status:
            _eq: published
    validation: null
    presets: null
    fields:
      - id
      - sort
      - name
      - sector
      - slug
      - impact
      - weight
      - feasibility_political
      - feasibility
      - feasibility_economical
      - verification_description
      - notes
      - description
      - date_updated
  - role: d09e2c25-a977-41fc-aa73-9238fcf20a9b
    collection: directus_translations
    action: read
    permissions: {}
    validation: {}
    presets: null
    fields:
      - "*"
