name: create_editor
icon: bolt
color: null
description: null
status: active
trigger: event
accountability: all
options:
  type: action
  scope:
    - items.create
  collections:
    - example
    - editors
operations:
  - name: create_user_api
    key: create_user_api
    type: request
    position_x: 19
    position_y: 1
    options:
      url: http://172.17.0.1:8081/users
      headers:
        - header: Authorization
          value: " Bearer jp9Sa0zDV4c_7wwX17TS-3VMnSMPKhDm"
operation_key: create_user_api
