name: createMunicipality
icon: bolt
color: null
description: create Municipality when Localteam is created
status: active
trigger: event
accountability: all
options:
  type: action
  scope:
    - items.create
  collections:
    - localteams
operations:
  - name: Create Data
    key: item_create_vf2y4
    type: item-create
    position_x: 24
    position_y: 1
    options:
      collection: municipalities
      payload:
        name: "{{$trigger.payload.municipality_name}}"
        localteam_id: "{{$trigger.key}}"
      emitEvents: true
      permissions: $full
operation_key: item_create_vf2y4
