name: createEditorUser
icon: bolt
color: null
description: create Editor-User when in the collection a editor is created
status: active
trigger: event
accountability: all
options:
  type: filter
  scope:
    - items.create
  collections:
    - editors
operations:
  - name: Add Editor
    key: operation_add_editor_ggff4
    type: operation-add-editor
    position_x: 11
    position_y: 25
    options:
      email: "{{$trigger.payload.email}}"
      localteam_id: "{{$trigger.payload.localteam_id}}"
operation_key: operation_add_editor_ggff4
