name: CreateEmptyRatings
icon: bolt
color: null
description: Creates an empty rating for the corresponding measure and localteam
status: active
trigger: operation
accountability: all
options:
  return: $all
operations:
  - name: Create Data
    key: item_create_8neoc
    type: item-create
    position_x: 19
    position_y: 1
    options:
      collection: ratings_measures
      payload:
        measure_id: "{{$last.measure_id}}"
        localteam_id: "{{$last.localteam_id}}"
      emitEvents: true
operation_key: item_create_8neoc
