name: create_slug
icon: format_color_text
color: null
description: Creates Slug from selected collections from field "name"
status: active
trigger: event
accountability: all
options:
  type: action
  scope:
    - items.create
  collections:
    - kommunen
    - massnahme
    - lokalteam
    - pages
    - massnahmen
operations:
  - name: Update Data
    key: item_update_e3ze4
    type: item-update
    position_x: 40
    position_y: 1
    options:
      collection: "{{$trigger.collection}}"
      payload:
        slug: "{{$last.text}}"
      key:
        - "{{ $trigger.key }}"
  - name: Slugify
    key: operation_slugify_z88zk
    type: operation-slugify
    position_x: 19
    position_y: 1
    options:
      text: "{{$trigger.payload.name}}"
    resolve_key: item_update_e3ze4
operation_key: operation_slugify_z88zk
