id: a9907a26-b678-44b1-b982-e5c8c78609bb
name: create_slug
icon: format_color_text
color: null
description: Creates Slug from selected collections from field "name"
status: active
trigger: event
accountability: all
options:
  type: action
  scope:
    - items.create
  collections:
    - kommunen
    - massnahme
    - lokalteam
operation: 12341830-6699-4dc6-8f43-d7818f726e57
date_created: 2023-09-08T13:44:19.788Z
user_created: c6574c61-b09c-47ed-ba71-2d1eee4d5594
operations:
  - id: 0eae510d-9773-4313-8469-8031980134ed
    name: Run Script
    key: exec_ketub
    type: exec
    position_x: 37
    position_y: 17
    options:
      code: |
        module.exports = async function(data) {
            let retData = data["$last"]
        	for (var i = 0; i < retData.length; i++){
          		retData[i]["orig_key"]=data["$trigger"]["key"]
          	}
            return {retData};
        }
    resolve: e6cd65d7-a64d-4a55-82ab-3d302c3ecb13
    reject: null
    flow: a9907a26-b678-44b1-b982-e5c8c78609bb
    date_created: 2023-09-09T00:28:53.504Z
    user_created: c6574c61-b09c-47ed-ba71-2d1eee4d5594
  - id: 0fe3c733-c24e-48da-9f3d-a9f1c1f018d9
    name: Read Data
    key: item_read_vahki
    type: item-read
    position_x: 19
    position_y: 1
    options:
      collection: massnahme
    resolve: 0eae510d-9773-4313-8469-8031980134ed
    reject: null
    flow: a9907a26-b678-44b1-b982-e5c8c78609bb
    date_created: 2023-09-09T00:00:26.123Z
    user_created: c6574c61-b09c-47ed-ba71-2d1eee4d5594
  - id: 12341830-6699-4dc6-8f43-d7818f726e57
    name: Update Data
    key: item_update_e3ze4
    type: item-update
    position_x: 30
    position_y: 2
    options:
      collection: "{{$trigger.collection}}"
      payload:
        slug: "{{$trigger.payload.slug}}"
      key:
        - "{{ $trigger.key }}"
    resolve: null
    reject: null
    flow: a9907a26-b678-44b1-b982-e5c8c78609bb
    date_created: 2023-09-08T18:11:00.477Z
    user_created: c6574c61-b09c-47ed-ba71-2d1eee4d5594
  - id: 419fe142-0b8c-4715-bd34-95f7f6a12f25
    name: Slugify
    key: operation_slugify_30ue3
    type: operation-slugify
    position_x: 2
    position_y: 17
    options:
      text: "{{$trigger.payload.name}}"
    resolve: null
    reject: null
    flow: a9907a26-b678-44b1-b982-e5c8c78609bb
    date_created: 2023-09-08T17:33:23.071Z
    user_created: c6574c61-b09c-47ed-ba71-2d1eee4d5594
  - id: 5172d9ed-7624-478d-9b39-52d5264e72a9
    name: Create Data
    key: item_create_s4ft8
    type: item-create
    position_x: 19
    position_y: 1
    options:
      collection: bewertungen
      payload:
        massnahme_id: "{{$trigger.id}}"
        kommune_id: "{{$trigger.orig_key}}"
    resolve: null
    reject: null
    flow: a9907a26-b678-44b1-b982-e5c8c78609bb
    date_created: 2023-09-09T00:56:16.027Z
    user_created: c6574c61-b09c-47ed-ba71-2d1eee4d5594
  - id: a3571097-0a55-4e7f-8d26-29693734dc7b
    name: Webhook / Request URL
    key: request_itxgt
    type: request
    position_x: 19
    position_y: 1
    options:
      url: http://172.17.0.1:8081/users
      headers:
        - header: Authorization
          value: " Bearer UZM2ioD_4-oTKuJZWDybzXtasCCJqwE7"
      body: |-
        {
        	"email": "{{$trigger.payload.email}}",
        	"password": "example",
          "lokalteam_id":  "{{$trigger.payload.lokalteam_id}}",
        	"role": "18781584-6436-49b7-a69d-69f4f5e5db8b"
        }
      method: POST
    resolve: null
    reject: null
    flow: a9907a26-b678-44b1-b982-e5c8c78609bb
    date_created: 2023-09-08T20:14:11.654Z
    user_created: c6574c61-b09c-47ed-ba71-2d1eee4d5594
  - id: e6cd65d7-a64d-4a55-82ab-3d302c3ecb13
    name: Trigger Flow
    key: trigger_3dghp
    type: trigger
    position_x: 25
    position_y: 37
    options:
      flow: b23c8383-f32e-49cb-b030-f63dfc7b321d
      iterationMode: serial
      payload: "{{$last['retData']}}"
    resolve: null
    reject: null
    flow: a9907a26-b678-44b1-b982-e5c8c78609bb
    date_created: 2023-09-09T00:05:14.607Z
    user_created: c6574c61-b09c-47ed-ba71-2d1eee4d5594
