name: newMeasureAfterUpdate
icon: bolt
color: null
description: when measure evaluation or choices_rating are changed create new
  measure and unpublish old one
status: active
trigger: event
accountability: all
options:
  type: filter
  scope:
    - items.update
  collections:
    - measures
operations:
  - name: Daten aktualisieren
    key: item_update_cwfoc
    type: item-update
    position_x: 24
    position_y: 20
    options:
      key: "{{$trigger.keys}}"
      payload: "{{$trigger.payload}}"
      collection: measures
  - name: Skript ausführen
    key: exec_ppjap
    type: exec
    position_x: 4
    position_y: 39
    options:
      code: >-
        module.exports = async function(data) {
        	let measures = data["$last"];
            if(!Array.isArray(measures)){
            measures =[measures];
            }
            let payload = data["$trigger"]["payload"];
            for (const measure of measures) {
                measure["id"] = null
                if ("description_evaluation_criteria" in payload) {
          			measure["description_evaluation_criteria"]=payload["description_evaluation_criteria"];
                }
                if("choices_rating" in payload) {
         				measure["choices_rating"]=payload["choices_rating"];
        		}
        	}

        	return measures;
        }
    resolve_key: item_update_urfgi
  - name: Daten aktualisieren
    key: item_update_urfgi
    type: item-update
    position_x: 22
    position_y: 39
    options:
      collection: measures
      permissions: $full
      key: "{{$trigger.keys}}"
      emitEvents: true
      payload:
        name: "{{name}}"
        status: draft
  - name: Daten lesen
    key: item_read_plcu3
    type: item-read
    position_x: 4
    position_y: 20
    options:
      key: "{{$trigger.keys}}"
      collection: measures
    resolve_key: exec_ppjap
  - name: Kondition
    key: condition_8sdox
    type: condition
    position_x: 22
    position_y: 1
    options:
      filter:
        _or:
          - $trigger:
              payload:
                description_evaluation_criteria:
                  _nnull: true
          - $trigger:
              payload:
                choices_rating:
                  _nnull: true
    resolve_key: item_read_plcu3
    reject_key: item_update_cwfoc
  - name: Daten erstellen
    key: item_create_y4046
    type: item-create
    position_x: 9
    position_y: 57
    options:
      collection: measures
      permissions: $full
      emitEvents: true
      payload: '"{{$exec_ppjap}}"'
operation_key: condition_8sdox
