name: newMassnahme_forEach_part
icon: bolt
color: null
description: triggers createsBewertung-Flow when a new Massnahme is created for
  each Lokalteam
status: active
trigger: event
accountability: all
options:
  type: action
  scope:
    - items.create
  collections:
    - massnahmen
operations:
  - name: add_massnahme_id
    key: add_massnahme_id
    type: exec
    position_x: 7
    position_y: 28
    options:
      code: |2-
         module.exports = async function(data) {
                    let retData = data["$last"]
                	for (var i = 0; i < retData.length; i++){
                  		retData[i]["massnahme_id"]=data["$trigger"]["key"]
                        retData[i]["lokalteam_id"]=retData[i]["id"]
                  	}
                    return {retData};
                }
    resolve_key: trigger_obzog
  - name: Trigger Flow
    key: trigger_obzog
    type: trigger
    position_x: 25
    position_y: 28
    options:
      flow: 5afc19fc-f9c8-441c-98e9-89efeb680093
      payload: "{{ $last.retData }}"
  - name: Read Data
    key: item_read_oe1gm
    type: item-read
    position_x: 19
    position_y: 1
    options:
      collection: lokalteam
    resolve_key: add_massnahme_id
operation_key: item_read_oe1gm
