name: unpublishOldMeasuresCreateNew
icon: bolt
color: null
description: cretese a mesure new measure with updated data and sets the old to unpublished
status: active
trigger: operation
accountability: all
options:
  return: $all
operations:
  - name: Daten erstellen
    key: item_create_duq7q
    type: item-create
    position_x: 21
    position_y: 19
    options:
      collection: measures
      payload: "{{exec_vb4gu.new_measure}}"
      emitEvents: true
    resolve_key: item_update_wdrgr
  - name: Daten aktualisieren
    key: item_update_b13k5
    type: item-update
    position_x: 3
    position_y: 19
    options:
      collection: measures
      key: "{{$last.old_measure.id}}"
      payload: "{{$last.old_measure}}"
    resolve_key: item_create_duq7q
  - name: Daten aktualisieren
    key: item_update_wdrgr
    type: item-update
    position_x: 3
    position_y: 35
    options:
      collection: ratings_measures
      payload:
        measure_published: false
      query:
        filter:
          measure_id:
            _eq: "{{$trigger.id}}"
  - name: Skript ausführen
    key: exec_vb4gu
    type: exec
    position_x: 19
    position_y: 1
    options:
      code: |-
        module.exports = async function(data) {
            let measure = data["$trigger"]
            let newMeasure = data["$trigger"]["new_measure"]
        	delete measure["new_measure"];
        	return {
           		"old_measure": measure,
                "new_measure":newMeasure
            };
        }
    resolve_key: item_update_b13k5
operation_key: exec_vb4gu
