name: unpublishedMeasure
icon: restore_from_trash
color: "#E01B24"
description: when measure is unpublished set flag in rating and set to draft
status: active
trigger: event
accountability: all
options:
  type: action
  scope:
    - items.update
  collections:
    - measures
operations:
  - name: Daten aktualisieren
    key: item_update_w3815
    type: item-update
    position_x: 4
    position_y: 23
    options:
      query:
        filter:
          measure_id:
            _in: "{{$trigger.keys}}"
      payload:
        measure_published: false
      collection: ratings_measures
      emitEvents: true
  - name: Condition
    key: condition_79sk5
    type: condition
    position_x: 21
    position_y: 2
    options:
      filter:
        $trigger:
          payload:
            status:
              _eq: draft
    resolve_key: item_update_w3815
operation_key: condition_79sk5
