name: "updateMeasure Trigger createEmpty Rating "
icon: bolt
color: null
description: triggers CreateEmptyRatings for each localteam  when a
  measure.status is updated to published
status: active
trigger: event
accountability: all
options:
  type: action
  scope:
    - items.update
  collections:
    - measures
operations:
  - name: Daten lesen
    key: item_read_0agul
    type: item-read
    position_x: 25
    position_y: 1
    options:
      collection: measures
      key: "{{$trigger.keys}}"
    resolve_key: condition_l1qrh
  - name: Condition
    key: condition_l1qrh
    type: condition
    position_x: 3
    position_y: 23
    options:
      filter:
        $trigger:
          payload:
            status:
              _eq: published
    resolve_key: item_read_djgzw
  - name: Trigger Flow
    key: trigger_cupdd
    type: trigger
    position_x: 21
    position_y: 39
    options:
      flow: 14c9927f-79d5-42e1-b145-873cc1f364ab
      payload: "{{$last.retData}}"
  - name: Read Data
    key: item_read_djgzw
    type: item-read
    position_x: 21
    position_y: 23
    options:
      collection: localteams
    resolve_key: exec_thpou
  - name: Run Script
    key: exec_thpou
    type: exec
    position_x: 4
    position_y: 39
    options:
      code: >2-
         module.exports = async function(data) {
                    let retData = [];
                	for (var i = 0; i < data["$last"].length; i++){
                        for (var j = 0; j < data["$trigger"]["keys"].length; j++){
                            let choice;
                            if(Array.isArray(data["item_read_0agul"])){
                            	 choice=data["item_read_0agul"][j]["choices_rating"]
                            }
                       		 else{
                                 choice = data["item_read_0agul"]["choices_rating"]
                            }
                            retData.push({
                               "localteam_id":data["$last"][i]["id"],
                                "measure_id": data["$trigger"]["keys"][j],
                                "choices": choice
                                     
                            })
                  		}
                    }
                    return {retData};
                }
    resolve_key: trigger_cupdd
operation_key: item_read_0agul
