name: updateMunicipality
icon: bolt
color: null
description: When Municpality.status is updated to publish calculate rank
status: active
trigger: event
accountability: all
options:
  type: action
  scope:
    - items.update
  collections:
    - municipalities
operations:
  - name: updatesRanks
    key: update_ranks_cun4d
    type: updateRanks
    position_x: 2
    position_y: 18
    options: {}
  - name: Condition
    key: condition_9x5et
    type: condition
    position_x: 19
    position_y: 1
    options:
      filter:
        $trigger:
          payload:
            status:
              _eq: published
    resolve_key: update_ranks_cun4d
operation_key: condition_9x5et
