id: f0b6ca68-da34-4a9a-9115-b21abbf1f74b
name: test_create_user_api
icon: bolt
color: null
description: Creates User When object is created in Collection
status: inactive
trigger: event
accountability: all
options:
  type: action
  scope:
    - items.create
  collections:
    - editors
operation: a3571097-0a55-4e7f-8d26-29693734dc7b
date_created: 2023-09-08T20:08:42.072Z
user_created: null
operations:
  - id: a3571097-0a55-4e7f-8d26-29693734dc7b
    name: Webhook / Request URL
    key: request_itxgt
    type: request
    position_x: 19
    position_y: 1
    options:
      url: http://172.17.0.1:8081/users
      headers:
        - header: Authorization
          value: " Bearer UZM2ioD_4-oTKuJZWDybzXtasCCJqwE7"
      body: |-
        {
        	"email": "{{$trigger.payload.email}}",
        	"password": "example",
          "lokalteam_id":  "{{$trigger.payload.lokalteam_id}}",
        	"role": "18781584-6436-49b7-a69d-69f4f5e5db8b"
        }
      method: POST
    resolve: null
    reject: null
    flow: b23c8383-f32e-49cb-b030-f63dfc7b321d
    date_created: 2023-09-08T20:14:11.654Z
    user_created: null