id: 2ba17127-df54-4938-aafb-759fe1223ee4
name: triggerCreateBewertungForEach
icon: bolt
color: null
description: bei erstellung einer Kommune triggert dieser flow
  createBewertungForEach für jede Maßnahme einmal
status: active
trigger: event
accountability: all
options:
  type: action
  scope:
    - items.create
  collections:
    - kommunen
operation: 0fe3c733-c24e-48da-9f3d-a9f1c1f018d9
date_created: 2023-09-08T23:58:48.946Z
user_created: null
operations:
  - id: 0eae510d-9773-4313-8469-8031980134ed
    name: Run Script
    key: exec_ketub
    type: exec
    position_x: 37
    position_y: 17
    options:
      code: |
        module.exports = async function(data) {
            let retData = data["$last"]
        	for (var i = 0; i < retData.length; i++){
          		retData[i]["orig_key"]=data["$trigger"]["key"]
          	}
            return {retData};
        }
    resolve: null
    reject: null
    flow: b23c8383-f32e-49cb-b030-f63dfc7b321d
    date_created: 2023-09-09T00:28:53.504Z
    user_created: null
  - id: 0fe3c733-c24e-48da-9f3d-a9f1c1f018d9
    name: Read Data
    key: item_read_vahki
    type: item-read
    position_x: 19
    position_y: 1
    options:
      collection: massnahme
    resolve: null
    reject: null
    flow: b23c8383-f32e-49cb-b030-f63dfc7b321d
    date_created: 2023-09-09T00:00:26.123Z
    user_created: null
  